const { Worker } = require('bullmq');
const Redis = require('ioredis');
const aiContent = require('./aiContent.service');
const aiRag = require('./aiRag.service');
const db = require('../models');
const logger = require('../utils/logger');

const { Course, Chapter, Lecture } = db.models;

const isTest = process.env.NODE_ENV === 'test';

let courseGenerationWorker;

if (!isTest) {
  const redisOptions = {
    maxRetriesPerRequest: null,
    ...(process.env.REDIS_URL && process.env.REDIS_URL.startsWith('rediss') && {
      tls: {
        rejectUnauthorized: false,
      },
    }),
  };

  let redisConnection;
  if (process.env.REDIS_URL) {
    redisConnection = new Redis(process.env.REDIS_URL, redisOptions);
  } else {
    redisConnection = new Redis({
      host: process.env.REDIS_HOST || '127.0.0.1',
      port: process.env.REDIS_PORT || 6379,
      ...redisOptions,
    });
  }

  redisConnection.on('error', (err) => {
    console.error('❌ [CourseGenerationWorker] Connection Error:', err.message);
  });

  // Worker xử lý job từ queue
  courseGenerationWorker = new Worker(
    'courseGenerationQueue',
    async (job) => {
      const { courseId, chapterIds, options, userId } = job.data;

      logger.info('COURSE_GENERATION_STARTED', {
        jobId: job.id,
        courseId,
        chapterIds,
        userId,
      });

      try {
        // Update course status
        await Course.update(
          { generationStatus: 'generating_content' },
          { where: { id: courseId } }
        );

        // Get chapters to generate
        const chapters = await Chapter.findAll({
          where: { id: chapterIds, courseId },
          order: [['order', 'ASC']],
        });

        const results = {
          success: [],
          failed: [],
        };

        // Generate content for each chapter sequentially to avoid AI overload
        for (const chapter of chapters) {
          try {
            // Get lectures for this chapter
            const lectures = await Lecture.findAll({
              where: { chapterId: chapter.id },
              order: [['order', 'ASC']],
            });

            // Generate content for each lecture
            for (const lecture of lectures) {
              try {
                // Generate lecture content using AI
                const contentResult = await aiContent.generateLectureContent(
                  courseId,
                  chapter.id,
                  {
                    title: lecture.title,
                    outline: lecture.description || '',
                    targetAudience: options.targetAudience || 'general',
                    difficulty: options.difficulty || 'intermediate',
                    estimatedDuration: lecture.estimatedDuration || 45,
                  }
                );

                // Update lecture with generated content
                await lecture.update({
                  content: contentResult.content,
                  aiNotes: `Generated by AI on ${new Date().toISOString()}`,
                });

                // Ingest lecture content to RAG for chat
                try {
                  await aiRag.ingestLecture(lecture.id, {
                    title: lecture.title,
                    chapterId: chapter.id,
                    courseId,
                  });
                  logger.info('LECTURE_INGESTED_TO_RAG', {
                    lectureId: lecture.id,
                    chapterId: chapter.id,
                    courseId,
                  });
                } catch (ragError) {
                  logger.warn('RAG_INGEST_FAILED', {
                    lectureId: lecture.id,
                    error: ragError.message,
                  });
                  // Continue even if RAG ingest fails
                }

                // Optionally generate quiz for this lecture
                if (options.generateQuizzes) {
                  try {
                    await aiContent.generateAndSaveQuiz(
                      lecture.id,
                      {
                        title: `Quiz: ${lecture.title}`,
                        description: `Quiz tự động tạo cho lecture "${lecture.title}"`,
                      },
                      {
                        questionCount: options.questionsPerLecture || 5,
                        questionTypes: ['multiple_choice', 'true_false'],
                        difficulty: options.difficulty || 'mixed',
                      },
                      userId
                    );
                  } catch (quizError) {
                    logger.warn('QUIZ_GENERATION_FAILED_FOR_LECTURE', {
                      lectureId: lecture.id,
                      error: quizError.message,
                    });
                    // Continue even if quiz generation fails
                  }
                }

                logger.info('LECTURE_CONTENT_GENERATED', {
                  lectureId: lecture.id,
                  chapterId: chapter.id,
                  courseId,
                });
              } catch (lectureError) {
                logger.error('LECTURE_GENERATION_FAILED', {
                  lectureId: lecture.id,
                  chapterId: chapter.id,
                  error: lectureError.message,
                });
                results.failed.push({
                  lectureId: lecture.id,
                  error: lectureError.message,
                });
              }

              // Delay between lectures to avoid rate limiting
              await new Promise((resolve) => setTimeout(resolve, 2000));
            }

            results.success.push(chapter.id);
          } catch (chapterError) {
            logger.error('CHAPTER_GENERATION_FAILED', {
              chapterId: chapter.id,
              error: chapterError.message,
            });
            results.failed.push({
              chapterId: chapter.id,
              error: chapterError.message,
            });
          }

          // Delay between chapters
          await new Promise((resolve) => setTimeout(resolve, 3000));
        }

        // Update course status based on results
        const allSuccessful = results.failed.length === 0;
        await Course.update(
          {
            generationStatus: allSuccessful ? 'completed' : 'failed',
            aiGenerated: true,
          },
          { where: { id: courseId } }
        );

        logger.info('COURSE_GENERATION_COMPLETED', {
          jobId: job.id,
          courseId,
          successCount: results.success.length,
          failedCount: results.failed.length,
        });

        return {
          success: allSuccessful,
          results,
          courseId,
        };
      } catch (error) {
        logger.error('COURSE_GENERATION_FAILED', {
          jobId: job.id,
          courseId,
          error: error.message,
          stack: error.stack,
        });

        // Update course status to failed
        await Course.update(
          { generationStatus: 'failed' },
          { where: { id: courseId } }
        );

        throw error;
      }
    },
    {
      connection: redisConnection,
      concurrency: 1, // Process one at a time to avoid AI overload
      limiter: {
        max: 1,
        duration: 5000, // 5 seconds between jobs
      },
    }
  );

  // Event handlers
  courseGenerationWorker.on('completed', (job, result) => {
    logger.info('COURSE_GENERATION_JOB_COMPLETED', {
      jobId: job.id,
      result,
    });
  });

  courseGenerationWorker.on('failed', (job, err) => {
    logger.error('COURSE_GENERATION_JOB_FAILED', {
      jobId: job.id,
      error: err.message,
    });
  });

  console.log('🔧 Course Generation Worker initialized');
} else {
  // Mock for test environment
  courseGenerationWorker = null;
}

module.exports = { courseGenerationWorker };
